name: Build and Publish

# stolen from https://github.com/joreilly/chip-8/blob/main/.github/workflows/build-and-publish-web.yml


# configure manual trigger
on:
  push:
    branches:
      - master
      - main


jobs:
  pages:
    name: Build and Publish to Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      # Setup Java 1.8 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Build application
      - name: Test and Build
        run: chmod +x ./gradlew && ./gradlew :composeApp:build

      - name: Copy "uninstantiated" file over (workaround for now)
        run: cp composeApp/build/compileSync/wasmJs/main/productionExecutable/kotlin/composeApp.uninstantiated.mjs composeApp/build/dist/wasmJs/productionExecutable

      # If main branch update, deploy to gh-pages
      - name: Deploy
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: composeApp/build/dist/wasmJs/productionExecutable # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch

  binaries:
    name: Build and Publish Executables
    runs-on: windows-latest
    steps:
      # Setup Java 1.8 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Publish Exe
        run: ./gradlew :composeApp:packageReleaseExe

      - name: Upload Exe
        uses: actions/upload-artifact@v4
        with:
          name: Checker Executable
          path: composeApp/build/compose/binaries/main-release/exe

      - name: Publish Msi
        run: ./gradlew :composeApp:packageReleaseMsi

      - name: Upload Msi
        uses: actions/upload-artifact@v4
        with:
          name: Checker Windows Installer
          path: composeApp/build/compose/binaries/main-release/msi

      - name: Publish Jar
        run: ./gradlew :composeApp:packageReleaseUberJarForCurrentOS

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: Checker Jar Executable
          path: composeApp/build/compose/jars