name: Build and Publish

# stolen from https://github.com/joreilly/chip-8/blob/main/.github/workflows/build-and-publish-web.yml


# configure manual trigger
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:

      # Setup Java 1.8 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Build application
      - name: Test and Build
        run: chmod +x ./gradlew && ./gradlew :composeApp:build

      - name: Copy "uninstantiated" file over (workaround for now)
        run: cp composeApp/build/compileSync/wasmJs/main/productionExecutable/kotlin/composeApp.uninstantiated.mjs composeApp/build/dist/wasmJs/productionExecutable

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3 # https://github.com/actions/upload-artifact/releases
        with:
          name: Click here to download
          path: composeApp/build/libs/composeApp-desktop.jar

      # If main branch update, deploy to gh-pages
      - name: Deploy
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: composeApp/build/dist/wasmJs/productionExecutable # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch